// Lugares del viaje. Datos de la guía turística (CSV) + metadatos de la bitácora.
// Editar aquí agrega o corrige un lugar en toda la página.
window.PLACES = [
  { s:"solheimajokull", c:"is", w:"Sólheimajökull",
    n:"Sólheimajökull", p:"SÓL-hei-ma-yö-kutl",
    d:"La lengua de glaciar donde se hacen las caminatas sobre hielo, rayada de ceniza negra del volcán de 2010.",
    yt:"Solheimajokull glacier hike Iceland",
    why:"Paisaje alienígena donde el hielo azul milenario se mezcla con vetas profundas de ceniza volcánica negra.",
    how:"A 2.5 horas de Reikiavik por la Ring Road (Ruta 1) hacia el sur. Desvío asfaltado hasta el estacionamiento.",
    time:"3-4 horas para tour guiado estándar. 45 min solo para el mirador.",
    hist:"Es una lengua del glaciar Mýrdalsjökull, situado entre los imponentes volcanes Katla y Eyjafjallajökull. Hoy es un claro testimonio del rápido deshielo por el cambio climático. Por ser parte de la inmensa capa de hielo de Mýrdalsjökull, su tamaño y relativa facilidad de acceso lo han convertido en un punto de referencia clave para glaciólogos. En las últimas décadas, ha retrocedido drásticamente, dejando a su paso una nueva laguna glaciar en constante expansión.",
    tips:["Nunca subir sin guía (grietas tapadas).", "Llevar botas rígidas.", "Respetar los letreros de límite sin equipo."],
    curio:"Las franjas negras son ceniza real de erupciones históricas del Katla, no tierra.",
    clothes:"Sistema de 3 capas (térmica, polar, impermeable). Rompevientos fuerte.",
    todo:["Caminata con crampones", "beber agua pura de los arroyos glaciares y probar la escalada en hielo"],
    cost:"Acceso libre al estacionamiento y mirador. Tour guiado: ~$100-130 USD.",
    hour:"Primera hora de la mañana (9:00 AM) para evitar a los grupos grandes de autobuses.",
    effort:"Exigente para subir al hielo. Accesibilidad nula para sillas de ruedas en el sendero de grava.",
    gear:"Funda impermeable para celular, mochila sellada, guantes táctiles para la cámara. Mapas offline GPS.",
    logis:"Estacionamiento gratuito por ahora. Baños limitados o de pago en la base. Usar Parka app si hay letreros.",
    food:"No hay comida en el lugar. Llevar barras energéticas. Parar a comer en Vík (Sopa de lava/cordero).",
    walk:"Caminata de 1.5 km (aprox 20 min) desde el auto hasta el frente de hielo. Terreno llano pero de grava suelta y arena gruesa, lo que exige esfuerzo al caminar; ideal para quienes pueden mantener un paso constante pero no recomendable para personas que buscan evitar distancias.",
    signal:"Pobre a nula cerca de las grietas. Es vital llevar mapas descargados offline.",
    planb:"Visitar el museo de lava LAVA Centre en Hvolsvöllur o la cueva de hielo indoor en Perlan (Reikiavik).",
    light:"100% dependiente de luz solar por seguridad y visibilidad de los colores.",
    booking:"Tours guiados: Reservar con al menos 2-4 semanas de anticipación en verano.",
    film:"Documental 'Chasing Ice'. (A menudo se confunde con el planeta de hielo de 'Interstellar', que se filmó en Svínafellsjökull)." },
  { s:"seljalandsfoss", c:"is", w:"Seljalandsfoss",
    n:"Seljalandsfoss", p:"SEL-ya-lands-fos",
    d:"Cascada de 60 metros por detrás de la cual se puede caminar. En octubre el sendero suele estar resbaloso.",
    yt:"Seljalandsfoss waterfall Iceland",
    why:"Puedes rodear completamente la cascada por detrás, ofreciendo una perspectiva fotográfica espectacular.",
    how:"Sobre la Ring Road, a 1 h 45 min de Reikiavik hacia el sur.",
    time:"45 minutos a 1 hora.",
    hist:"En la antigüedad, el acantilado del que cae esta imponente cascada de 60 metros marcaba la verdadera línea costera del océano en Islandia. Con el paso de los milenios, el peso de los glaciares en la isla disminuyó, provocando que el terreno se elevara (rebote isostático) y alejando el mar. Hoy, su agua pura proviene del constante deshielo del infame volcán recubierto de glaciar, Eyjafjallajökull.",
    tips:["Rocas muy resbaladizas.", "Cámara se empapará.", "Pagar parquímetro obligatorio."],
    curio:"El agua que te salpica viene del glaciar del volcán que detuvo el tráfico aéreo europeo en 2010.",
    clothes:"Chamarra y pantalones 100% impermeables (Gore-Tex).",
    todo:["Caminar por detrás del agua y visitar la cascada vecina oculta", "Gljúfrabúi"],
    cost:"Entrada gratuita. Estacionamiento de pago (~$6 USD).",
    hour:"Al atardecer, la luz dorada choca de frente con la cortina de agua.",
    effort:"Bajo para verla de frente. El sendero trasero exige balance y cuidado por escalones lodosos.",
    gear:"Lente gran angular. Paños de microfibra constantes para limpiar el lente de la brisa. Funda de lluvia para cámara.",
    logis:"Estacionamiento de pago (app Parka). Baños de pago y una pequeña tienda de souvenirs.",
    food:"Suele haber un food truck de café caliente y donas frescas en el estacionamiento.",
    walk:"La cascada principal está a literal 100 metros del estacionamiento por un camino de tierra compacta (2 min a pie), lo que la hace ultra-accesible y perfecta para minimizar caminatas. El sendero trasero sí tiene rocas irregulares y mojadas.",
    signal:"Buena señal móvil al estar justo en la carretera principal.",
    planb:"El LAVA Centre (museo interactivo de volcanes a 25 min de regreso).",
    light:"Se ve mejor con luz, pero está iluminada artificialmente de noche durante el invierno.",
    booking:"No requiere reservas.",
    film:"Aparece en 'The Amazing Race' y en el video musical de Justin Bieber 'I'll Show You'." },
  { s:"skogafoss", c:"is", w:"Skógafoss",
    n:"Skógafoss", p:"SKÓU-ga-fos",
    d:"Veinticinco metros de ancho y sesenta de caída. Hay 527 escalones para subir al mirador, opcionales.",
    yt:"Skogafoss waterfall Iceland",
    why:"Imponente cortina de agua de 60x25 metros que crea arcoíris dobles casi siempre que hay sol.",
    how:"A 30 minutos al este de Seljalandsfoss por la Ring Road.",
    time:"1 a 1.5 horas.",
    hist:"Cuenta el folclore local que el primer colono vikingo de la región, Þrasi Þórólfsson, escondió un cofre repleto de oro detrás de esta densa cortina de agua en el año 900. Se dice que durante siglos, los locales vieron el brillo del oro a través del agua. Muchos buscaron el tesoro, y la leyenda afirma que solo lograron arrancar una de las argollas del cofre, la cual hoy se exhibe en la puerta de la iglesia del museo vecino.",
    tips:["Los 527 escalones exigen cardio.", "No cruzar cuerdas de seguridad.", "Brisa constante."],
    curio:"Inicia aquí la famosa ruta de senderismo Fimmvörðuháls.",
    clothes:"Ropa térmica transpirable, chamarra impermeable ligera.",
    todo:["Fotografiar arcoíris y subir al mirador superior"],
    cost:"Totalmente gratis (entrada y estacionamiento).",
    hour:"Día soleado a mediodía para asegurar los arcoíris.",
    effort:"Cero esfuerzo para verla de frente. Esfuerzo aeróbico altísimo para subir la escalera.",
    gear:"Filtro polarizador (CPL) para capturar mejor los colores del arcoíris. Tripié pesado (mucho viento).",
    logis:"Estacionamiento gratis (suelo de grava). Baños gratuitos junto al área de acampar.",
    food:"El restaurante de Hotel Skógafoss o el café del museo Skógar (probar pastel tradicional).",
    walk:"Desde el auto hasta la base de la cascada hay 250 metros (unos 3-4 min). Terreno completamente llano de grava de río gris. Muy fácil caminar para cualquier persona que requiera evitar esfuerzos físicos. Los 527 escalones de la cima son totalmente opcionales.",
    signal:"Buena señal móvil general.",
    planb:"El Museo Folkórico de Skógar (Skógasafn) justo al lado, excelente muestra bajo techo de casas de turba vikingas.",
    light:"Necesita sol para los arcoíris, pero el caudal es impresionante en días nublados.",
    booking:"No aplica.",
    film:"Thor: The Dark World, The Secret Life of Walter Mitty, Vikings (Serie)." },
  { s:"reynisfjara", c:"is", w:"Reynisfjara", we:"Reynisfjara",
    n:"Reynisfjara", p:"REI-nis-fya-ra",
    d:"Playa de arena negra con columnas de basalto. Sus olas son peligrosas: nunca darle la espalda al mar.",
    yt:"Reynisfjara black sand beach Iceland",
    why:"Playa de arena negra rodeada de columnas de basalto hexagonales y farallones marinos dramáticos.",
    how:"Cerca de Vík, a 2.5 horas de Reikiavik, desvío de la Ruta 1.",
    time:"1 hora.",
    hist:"Su inconfundible arena negra no es realmente 'arena' en el sentido coralino, sino el resultado de ríos de magma incandescente del volcán Katla que se enfriaron violenta y rápidamente al chocar con las gélidas aguas del Atlántico Norte, para luego ser triturados por las olas a lo largo de milenios. Según el folclore islandés, las gigantescas rocas dentadas que se alzan en el mar (Reynisdrangar) son en realidad trolls petrificados que intentaban arrastrar un barco a la orilla, pero fueron sorprendidos por la luz del amanecer.",
    tips:["OLAS SNEAKER mortales, nunca des la espalda al mar.", "Vientos huracanados.", "Respetar zonas rojas del semáforo."],
    curio:"Fue catalogada como una de las playas no tropicales más hermosas del mundo.",
    clothes:"Rompevientos pesado, bufanda, gorro ajustado. Ropa que bloquee el viento marino.",
    todo:["Admirar las columnas de basalto (Hálsanefshellir) y ver frailecillos en verano"],
    cost:"Entrada gratis. Parking de pago.",
    hour:"Muy temprano (8 AM) o al atardecer para evadir autobuses.",
    effort:"Bajo para llegar, pero caminar en la arena es algo pesado. Zona con rampas en la entrada.",
    gear:"Evitar cambiar lentes aquí; la sal, arena y el viento pueden arruinar el sensor. Celular con estabilizador.",
    logis:"Estacionamiento pavimentado de pago. Baños de pago y una cafetería central.",
    food:"Black Beach Restaurant ofrece sopas calientes y estofado islandés (Kjötsúpa).",
    walk:"Desde el café hasta tocar la arena hay solo 50 metros pavimentados. Caminar hasta las columnas de basalto exige atravesar unos 300 metros sobre guijarros volcánicos sueltos y arena negra gruesa, lo que cansa las piernas rápidamente. A tener en cuenta para regular el desgaste físico.",
    signal:"Muy buena.",
    planb:"El espectáculo Lava Show en el pueblo de Vík (ves cómo derriten roca volcánica real en interiores).",
    light:"Se puede disfrutar con nubes y lluvia (de hecho le da una estética más oscura e imponente).",
    booking:"No aplica.",
    film:"Game of Thrones (Eastwatch-by-the-Sea / Guardaoriente), Star Wars: Rogue One, Noah, Star Trek: Into Darkness." },
  { s:"circulo-dorado", c:"is", w:"Gullfoss", we:"Gullfoss",
    n:"Círculo Dorado", p:"Þingvellir · Geysir · Gullfoss",
    d:"El parque donde se separan dos placas tectónicas, el géiser original y una cascada de dos niveles.",
    yt:"Golden Circle Iceland Thingvellir Geysir Gullfoss",
    why:"El resumen perfecto de Islandia: tectónica de placas, actividad geotérmica y cascadas masivas.",
    how:"Ruta circular a las afueras de Reikiavik.",
    time:"6 a 8 horas todo el circuito.",
    hist:"Þingvellir no solo es un asombroso valle de rift tectónico, sino el corazón histórico de Islandia: aquí los vikingos fundaron el Alþingi, el primer parlamento nacional al aire libre del mundo, en el año 930 d.C., donde se recitaban leyes de memoria. Más adelante en la ruta, el valle geotérmico de Haukadalur alberga el Gran Geysir, que documentó por primera vez en Europa esta actividad explosiva. Y Gullfoss, la 'Cascada Dorada', fue heroicamente protegida a principios de 1900 por Sigríður Tómasdóttir, la primera ecologista islandesa, quien amenazó con arrojarse al abismo si se construía allí una represa hidroeléctrica extranjera.",
    tips:["Caminos de hielo en invierno.", "No tocar agua de géiseres (100°C).", "Multitudes en cada parada."],
    curio:"El Gran Geysir dio nombre a este fenómeno global.",
    clothes:"Capas versátiles (chamarras de quitar y poner fácil al bajar del coche).",
    todo:["Caminar entre las placas tectónicas", "fotografiar Strokkur estallando y sentir la fuerza de Gullfoss"],
    cost:"Gullfoss/Geysir gratis. Þingvellir cobra parking (~$7 USD).",
    hour:"Iniciar la ruta a las 7 AM o a partir de las 3 PM para ir a contracorriente de los tours.",
    effort:"Generalmente muy accesible. Caminos de madera y asfalto en los 3 puntos principales.",
    gear:"Burst mode (modo ráfaga) configurado en cámara/celular para capturar la erupción de Strokkur en el milisegundo exacto.",
    logis:"Excelentes centros de visitantes en cada parada con enormes estacionamientos y baños grandes.",
    food:"La Sopa de Cordero (Meat Soup) en la cafetería del Centro de Visitantes de Gullfoss es tradicional.",
    walk:"Þingvellir: Mirador principal a 100m (plano/madera). Geysir: A 200m del estacionamiento (plano/tierra). Gullfoss: Mirador superior a 50m del parking (plano/asfalto). Excelentes lugares para caminatas cortas, pausadas y sin esfuerzo cardíaco, maximizando las vistas en pocos pasos.",
    signal:"Excelente en todos los puntos turísticos.",
    planb:"Visitar las aguas termales cubiertas/resguardadas como Secret Lagoon o Fontana Geothermal Baths en la misma ruta.",
    light:"Preferible luz natural para todo, especialmente para los colores del agua en Þingvellir.",
    booking:"No aplica a menos que tomes un tour en autobús desde Reikiavik.",
    film:"Game of Thrones (Þingvellir fue la Puerta de la Sangre / Bloody Gate), Tomb Raider." },
  { s:"auroras", c:"is", w:"Aurora polar", we:"Aurora",
    n:"Auroras boreales", p:"Norðurljós",
    d:"Finales de octubre es de las mejores épocas: noches largas y cielo oscuro. Nunca están garantizadas.",
    yt:"northern lights Iceland aurora borealis",
    why:"Un espectáculo atmosférico irrepetible donde partículas solares chocan con el campo magnético terrestre, creando ríos de luz vibrante.",
    how:"Necesitas alejarte de la contaminación lumínica. Puede ser manejando 30 min fuera de Reikiavik o tomando un tour especializado ('Northern Lights Hunt').",
    time:"Excursiones duran 3-4 horas (generalmente de 9 PM a 1 AM).",
    hist:"En la mitología nórdica, algunos creían que las auroras eran los reflejos de las armaduras de las Valquirias guiando a los caídos al Valhalla.",
    tips:["Solo son visibles de septiembre a abril.", "No están garantizadas (dependen del clima espacial y nubosidad).", "No uses flash en tu cámara ni lámparas que arruinen la visión nocturna de otros."],
    curio:"La cámara de tu celular capta los colores (verde, rosa) mucho más intensos de lo que el ojo humano los percibe en la oscuridad.",
    clothes:"Ropa térmica extrema. Estarás de pie, estático, a la intemperie en la madrugada. Lleva doble calcetín, guantes gruesos y calentadores de manos químicos si es posible.",
    todo:["Llevar un trípode para la cámara (esencial para largas exposiciones) y usar aplicaciones como 'Aurora' para monitorear el índice KP"] },
  { s:"hallgrimskirkja", c:"is", w:"Hallgrímskirkja", we:"Hallgrímskirkja",
    n:"Hallgrímskirkja", p:"HATL-grims-kir-kya",
    d:"La iglesia que se ve desde toda la ciudad. Su torre da la mejor vista de Reikiavik.",
    yt:"Hallgrimskirkja Reykjavik church",
    why:"El ícono arquitectónico de Reikiavik. Su diseño imita las columnas de basalto de Islandia y su torre ofrece la mejor vista de los techos coloridos de la ciudad.",
    how:"En el centro de Reikiavik, accesible caminando desde casi cualquier punto de la ciudad.",
    time:"45 minutos a 1 hora.",
    hist:"Se tardó 41 años en construir (1945-1986) y fue diseñada por Guðjón Samúelsson, quien se inspiró en la geología extrema de la isla.",
    tips:["La iglesia es gratuita, pero subir a la torre tiene costo.", "A veces cierran la torre si hay misa o conciertos de órgano.", "Respeta el silencio, sigue siendo un templo activo."],
    curio:"Su órgano tiene 5,275 tubos de metal y pesa 25 toneladas.",
    clothes:"Ropa casual de ciudad. El viento en lo alto de la torre puede ser muy fuerte y frío por las ventanas abiertas.",
    todo:["Pagar el ticket de la torre para fotos panorámicas, ver la estatua del vikingo Leif Erikson (donada por EE", "UU.) y escuchar el órgano"] },
  { s:"aguas-termales", c:"is", w:"Laguna Azul (Islandia)", we:"Blue Lagoon (geothermal spa)",
    n:"Aguas termales", p:"Sky Lagoon · Blue Lagoon",
    d:"Meterse a agua caliente con el aire a cinco grados. Se reservan con día y hora.",
    yt:"Sky Lagoon Blue Lagoon Iceland",
    why:"Spas geotermales de lujo que contrastan el frío islandés con agua caliente curativa.",
    how:"Blue Lagoon cerca del aeropuerto (45 min). Sky Lagoon cerca del centro de Reikiavik (15 min).",
    time:"2.5 a 4 horas.",
    hist:"Contrario a la creencia popular de que es un fenómeno natural intacto, la icónica Blue Lagoon se originó accidentalmente en 1976 debido a los escurrimientos de agua sobrecalentada rica en sílice desechada por la planta de energía geotérmica adyacente, Svartsengi. Con el tiempo, los locales notaron que bañarse allí curaba enfermedades de la piel como la psoriasis. En contraste, el más reciente Sky Lagoon es un complejo moderno meticulosamente diseñado desde cero para honrar la ancestral cultura de baño termal islandesa fusionada con impresionantes vistas de 'infinity pool' hacia el gélido Océano Atlántico.",
    tips:["Ducha desnuda previa obligatoria.", "Sílice daña el cabello (usar mucho acondicionador sin enjuagar).", "Quitarse joyas de plata (el azufre las ennegrece)."],
    curio:"El agua de Blue Lagoon se renueva por completo cada 48h.",
    clothes:"Traje de baño. Sandalias opcionales.",
    todo:["Mascarillas de barro y el 'Ritual de 7 pasos' (sauna", "neblina fría", "exfoliante) en Sky Lagoon"],
    cost:"Desde $70 hasta $150 USD dependiendo del paquete (con/sin batas y bebidas).",
    hour:"Primera hora para agua prístina o última hora (9 PM) para intentar ver auroras en el agua.",
    effort:"Cero esfuerzo, relajación total. Totalmente accesible para sillas de ruedas (rampas y grúas de agua).",
    gear:"Funda sumergible para el celular obligatoria. No llevar cámaras profesionales grandes al agua por la neblina ácida.",
    logis:"Vestidores modernos, regaderas con shampoo/acondicionador incluido. Guarda equipaje grande.",
    food:"Restaurante Lava en Blue Lagoon (gourmet costoso) o snacks saludables en los bares húmedos dentro de las lagunas.",
    walk:"Estacionamiento a unos 150m de la entrada por pasarelas impecables. Distancias de vestidores a piscinas son de 20 metros. Ideal para personas mayores o con nula movilidad.",
    signal:"Excelente WiFi en ambos complejos.",
    planb:"Las aguas están calientes siempre (38°C), incluso en tormentas de nieve, ¡lo que mejora la experiencia de contraste!",
    light:"Irrelevante. Ambas son mágicas de noche o de día.",
    booking:"Blue Lagoon: ¡Obligatorio reservar con 1-2 meses de anticipación! Sky Lagoon: 2 semanas mínimo.",
    film:"Hostel Part II (Blue Lagoon), The Fifth Estate." },
  { s:"jokulsarlon", c:"is", w:"Jökulsárlón",
    n:"Jökulsárlón y Playa de los Diamantes", p:"YÖ-kul-sar-lon",
    d:"Laguna glaciar donde flotan icebergs que salen al mar y quedan varados en arena negra.",
    yt:"Jokulsarlon glacier lagoon Diamond Beach Iceland",
    why:"Icebergs gigantes azules y milenarios flotando en una laguna y varados como joyas en arena negra.",
    how:"A unas 5 h de Reikiavik, extremo este de la costa sur.",
    time:"2 a 3 horas.",
    hist:"Curiosamente, esta inmensa laguna glaciar (que hoy resulta ser el lago más profundo de toda Islandia, con casi 300 metros de profundidad) ni siquiera existía antes de 1930. Se originó y sigue formándose debido al dramático y veloz retroceso del glaciar Breiðamerkurjökull provocado por el calentamiento de las temperaturas. Año con año la laguna crece, llenándose de icebergs azules que se desprenden de la masa de hielo, flotan por meses y finalmente son arrastrados por la marea hacia el mar y de vuelta a la orilla.",
    tips:["No subirse nunca a los icebergs.", "Cuidado con aves agresivas (Skúas).", "Frío extremo por viento glaciar."],
    curio:"El hielo azul brillante indica que está tan comprimido que no tiene burbujas de aire.",
    clothes:"Rompevientos super pesado, guantes térmicos. Temperaturas caen drásticamente por vientos catabáticos.",
    todo:["Tour en bote anfibio o zodiac para esquivar icebergs", "Fotografía en Diamond Beach"],
    cost:"Laguna y playa gratis. Parking de pago. Tour Zodiac ~$100 USD.",
    hour:"Amanecer o atardecer (la luz dorada refracta mágico en el hielo en la arena).",
    effort:"Cero esfuerzo para ver la laguna desde arriba. Bajar a la playa es un poco irregular.",
    gear:"Baterías extra en bolsillos interiores calientes (el frío las drena al 50% en minutos). Lente macro para detalles de hielo.",
    logis:"Estacionamiento de grava (se paga por app). Hay sanitarios (pueden saturarse) y carritos de comida.",
    food:"Food trucks venden 'Fish and Chips' o sopa de langosta (Lobster Soup) deliciosa para calentar el cuerpo.",
    walk:"La laguna es visible literalmente caminando 2 minutos por una rampa de grava suave (50 metros). Para Diamond Beach, hay que caminar unos 150 metros cruzando un puente peatonal y bajando a arena suelta. Muy poco desgaste físico en general.",
    signal:"Buena cerca de la carretera.",
    planb:"Centro de visitantes de Skaftafell (cine documental y exposición glaciar, a 45 min).",
    light:"Fundamental. Sin luz, el hielo no refleja el azul y los diamantes no brillan.",
    booking:"Tours en barco Zodiac se agotan semanas antes. Botes anfibios tienen más disponibilidad.",
    film:"Batman Begins, James Bond (Die Another Day, A View to a Kill), Lara Croft: Tomb Raider." },
  { s:"dyrholaey", c:"is", w:"Dyrhólaey",
    n:"Dyrhólaey", p:"DIR-jó-la-ei",
    d:"Promontorio con un arco de piedra en el mar y vista de kilómetros de playa negra.",
    yt:"Dyrholaey Iceland viewpoint",
    why:"Un promontorio espectacular con un arco de roca volcánica masivo sobre el mar. Ofrece las mejores vistas panorámicas de las playas negras y los glaciares a lo lejos.",
    how:"Cerca de Vík, un desvío antes de llegar a Reynisfjara.",
    time:"45 minutos a 1 hora.",
    hist:"Solía ser una isla de origen volcánico que se unió a tierra firme. Su faro estilo 'castillo' data de 1927.",
    tips:["El camino de subida al faro superior puede ser de terracería empinada (mejor ir en 4x4 si ha llovido).", "Cierra en temporada de anidación de aves (mayo-junio) ciertas horas al día.", "Vientos que pueden derribarte."],
    curio:"El arco de piedra es tan grande que pequeñas avionetas han volado a través de él en maniobras acrobáticas.",
    clothes:"Rompevientos pesado y calzado para terreno irregular.",
    todo:["Observar frailecillos (puffins) desde lo alto de los acantilados a unos pocos metros de distancia durante el verano y disfrutar la vista ininterrumpida de las playas negras"] },
  { s:"fjadrargljufur", c:"is", w:"Fjaðrárgljúfur",
    n:"Fjaðrárgljúfur", p:"FIAZ-rar-gliú-vur",
    d:"Cañón musgoso de 100 metros de profundidad con un sendero por el filo.",
    yt:"Fjadrargljufur canyon Iceland",
    why:"Un cañón místico y serpenteante de 100 metros de profundidad tapizado por completo del verde intenso del musgo ártico.",
    how:"A unos 10 minutos de la Ring Road cerca del pueblo de Kirkjubæjarklaustur (a 3.5 horas de Reikiavik).",
    time:"1 a 1.5 horas.",
    hist:"Se formó al final de la última Edad de Hielo, hace unos 9,000 años, por la erosión progresiva del agua de deshielo glaciar sobre roca palagonítica.",
    tips:["PROHIBIDO SALIRSE DEL SENDERO CERCADO. El musgo tarda décadas en crecer y pisarlo lo destruye.", "El camino se enloda mucho tras las lluvias.", "No volar drones sin permiso."],
    curio:"Se cerró temporalmente en 2019 porque la popularidad del video musical de Justin Bieber atrajo multitudes que estaban destruyendo el frágil ecosistema.",
    clothes:"Botas impermeables (habrá charcos y lodo) y ropa de senderismo ligera si es verano.",
    todo:["Caminar hasta el mirador final donde cae la cascada, y apreciar los intrincados pliegues de la roca desde arriba"] },
  { s:"kerid", c:"is", w:"Kerið",
    n:"Kerið", p:"KE-rith",
    d:"Cráter volcánico con un lago turquesa en el fondo y laderas rojas.",
    yt:"Kerid crater Iceland",
    why:"Un cráter volcánico de tonos rojos oscuros que alberga un lago casi perfectamente circular de color aguamarina brillante.",
    how:"En la ruta del Círculo Dorado, a unos 15 minutos del pueblo de Selfoss.",
    time:"45 minutos.",
    hist:"A diferencia de otros volcanes, Kerið no explotó; más bien, tras la erupción hace 3,000 años, la cámara de magma se vació y colapsó sobre sí misma.",
    tips:["Hay una pequeña tarifa de entrada (unos 4 USD) para conservación, tener tarjeta a la mano.", "En invierno el sendero de bajada al lago es muy resbaladizo."],
    curio:"La acústica en el fondo del cráter es tan buena que a veces se organizan pequeños conciertos en balsas flotando en el lago.",
    clothes:"Chamarra corta-vientos ligera para bajar y subir el cráter, calzado de suela con buena tracción.",
    todo:["Caminar por todo el borde superior para apreciar los contrastes de color (roca, musgo verde y agua) y bajar por las escaleras hasta la orilla del lago"] },
  { s:"silfra", c:"is", w:"Silfra",
    n:"Silfra", p:"SIL-vra",
    d:"Grieta entre las placas tectónicas donde se hace snorkel en agua de deshielo transparente.",
    yt:"Silfra snorkeling Thingvellir Iceland",
    why:"Es el único lugar del mundo donde puedes hacer snorkel o bucear directamente entre dos placas tectónicas continentales, en agua de pureza incomparable.",
    how:"Ubicado dentro del Parque Nacional Þingvellir (Círculo Dorado).",
    time:"2.5 a 3 horas (incluyendo la preparación del traje seco y la actividad de 40 min en el agua).",
    hist:"El agua proviene del deshielo del glaciar Langjökull. Al filtrarse durante décadas a través de roca de lava porosa, la química del agua se vuelve excepcionalmente prístina.",
    tips:["Requiere buena condición física: el equipo de traje seco aprieta mucho en el cuello y muñecas.", "No puedes tocar el fondo ni las paredes para evitar levantar sedimentos.", "Si sufres claustrofobia severa por los trajes ajustados, evítalo."],
    curio:"Para un entusiasta de mantener parámetros perfectos de agua, esto es fascinante: el agua está tan filtrada que la visibilidad subacuática supera los 100 metros. Y sí, te la puedes beber mientras nadas.",
    clothes:"Ropa interior térmica (leggings y playera manga larga ajustada) para usar debajo del traje seco. Dos pares de calcetines gruesos.",
    todo:["Hacer snorkel para flotar sobre el 'Big Crack' y la 'Catedral de Silfra', observando los tonos azules eléctricos submarinos"] },
  { s:"ballenas", c:"is", w:"Ballena jorobada", we:"Whale watching",
    n:"Avistamiento de ballenas", p:"Puerto viejo de Reikiavik",
    d:"Salida en barco desde el puerto para ver ballenas jorobadas, minke y delfines de hocico blanco.",
    yt:"whale watching Reykjavik Iceland",
    why:"Islandia es uno de los mejores destinos europeos para ver cetáceos en su hábitat salvaje, incluyendo ballenas jorobadas, minke y orcas.",
    how:"Los barcos salen directamente del Puerto Viejo (Old Harbour) en el centro de Reikiavik.",
    time:"3 horas (barco tradicional) o 2 horas (lancha rápida RIB).",
    hist:"Islandia tiene un pasado complejo con la caza de ballenas, pero hoy la industria del avistamiento turístico genera mucho más valor económico y de conservación.",
    tips:["MAREO: El mar de Islandia puede ser picado. Si eres propenso, toma medicina 30 min antes de abordar.", "Las lanchas RIB no son aptas para personas con problemas de espalda.", "No está garantizado verlas, aunque hay alta probabilidad."],
    curio:"Las ballenas jorobadas migran miles de kilómetros desde el Caribe hasta Islandia solo para alimentarse en sus aguas ricas en nutrientes durante el verano.",
    clothes:"Las empresas te prestan un overol térmico gigante. Debajo, lleva gorro, guantes y chamarra térmica (hace muchísimo frío mar adentro, incluso en verano).",
    todo:["Elegir un tour en lancha RIB para mayor cercanía (si la espalda lo permite), y estar atento a los frailecillos en el agua mientras buscas el soplo de las ballenas"] },
  { s:"reykjanes", c:"is", w:"Península de Reykjanes", we:"Reykjanes",
    n:"Península de Reykjanes", p:"REI-kya-nes",
    d:"Campos de lava, el puente entre continentes y el vapor de Gunnuhver, junto al aeropuerto.",
    yt:"Reykjanes peninsula Iceland Bridge Between Continents Gunnuhver",
    why:"Paisaje lunar crudo, con campos de lava activa, fumarolas humeantes y acantilados abruptos. Sientes que la tierra está hirviendo debajo de ti.",
    how:"Es la península donde está el aeropuerto principal (Keflavík), a unos 40 min de Reikiavik.",
    time:"Medio día para recorrer varios puntos (Gunnuhver, Puente, Fagradalsfjall).",
    hist:"Después de 800 años inactiva, esta península despertó volcánicamente en 2021 y ha tenido múltiples erupciones recientes que han modificado los mapas.",
    tips:["Estar atento a las alertas gubernamentales (safetravel.is) sobre erupciones o gases tóxicos.", "En Gunnuhver, no salgas de las pasarelas de madera; el lodo hirviente quema zapatos y piel al instante.", "Los vientos aquí tiran puertas de coches (ábrelas con ambas manos)."],
    curio:"La leyenda dice que el respiradero geotermal Gunnuhver recibe su nombre de 'Gunna', el fantasma de una bruja vengativa que fue arrojada allí por un sacerdote.",
    clothes:"Chamarra gruesa y protección para la cara (bufanda/cuello) porque el viento sopla muy duro desde el océano abierto.",
    todo:["Caminar por el 'Puente entre continentes' (Midlina) para cruzar simbólicamente de Eurasia a Norteamérica, y ver las ollas de lodo burbujeante en Gunnuhver"] },
  { s:"perlan-harpa", c:"is", w:"Harpa (Reikiavik)", we:"Harpa (concert hall)",
    n:"Perlan y Harpa", p:"PER-lan · HAR-pa",
    d:"El museo con cueva de hielo artificial y planetario, y la sala de conciertos de fachada de cristal.",
    yt:"Perlan Harpa Reykjavik",
    why:"Perlan es un museo inmersivo interactivo clave para entender la naturaleza islandesa. Harpa es una obra maestra de la arquitectura moderna con cristales que imitan escamas.",
    how:"Ambos en Reikiavik. Harpa está en el puerto (centro). Perlan está en una colina, accesible en bus o coche (10 min del centro).",
    time:"2 a 3 horas para Perlan. 45 min para Harpa (si no entras a un concierto).",
    hist:"Perlan fue construido sobre los gigantescos tanques de agua caliente que abastecían la ciudad. Harpa sobrevivió a la crisis financiera de 2008 gracias al esfuerzo conjunto de los ciudadanos.",
    tips:["El túnel de hielo en Perlan está a -15°C, abrigate bien.", "En Harpa, respeta las áreas privadas para músicos.", "Si reservas un concierto en Harpa, llega con antelación."],
    curio:"La fachada de Harpa (diseñada por Olafur Eliasson) cambia de color y textura según la luz del sol, simulando las auroras boreales y el hielo.",
    clothes:"Ropa de ciudad. Para la cueva de hielo de Perlan te prestarán chalecos si hace falta, pero es mejor llevar tu chamarra.",
    todo:["En Perlan: caminar por la cueva de hielo real de 100 metros bajo techo, ver el show de planetario de auroras y visitar el mirador 360°", "En Harpa: fotografiar el juego de luces y sombras en los pasillos de cristal"] },
  { s:"rijksmuseum", c:"nl", w:"Rijksmuseum",
    n:"Rijksmuseum", p:"RÍKS-mu-se-um",
    d:"La Ronda de Noche de Rembrandt y La Lechera de Vermeer, a diez minutos del hotel.",
    yt:"Rijksmuseum Amsterdam tour",
    why:"Mayor colección mundial de arte y artefactos del Siglo de Oro neerlandés.",
    how:"Museumplein en Ámsterdam, accesible en tranvía o caminando desde el centro.",
    time:"3 a 4 horas.",
    hist:"El museo fue concebido y fundado inicialmente en La Haya en 1800 para emular el orgullo nacional y el modelo del famoso Louvre de París. Pocos años después, fue trasladado a Ámsterdam por orden directa del rey Luis Bonaparte (hermano de Napoleón). El majestuoso edificio actual fue diseñado por Pierre Cuypers e inaugurado en 1885, combinando asombrosamente los estilos góticos y renacentistas. Durante la devastación de la Segunda Guerra Mundial, sus mayores obras maestras, incluida 'La Ronda de Noche', fueron escondidas apresuradamente en búnkeres y cuevas para salvarlas de los bombardeos y el saqueo nazi.",
    tips:["Silencio y respeto en las galerías.", "Bolsos/mochilas grandes van al guardarropa.", "No usar flash."],
    curio:"Tiene un pasaje público ciclista que cruza el edificio por la mitad (único en el mundo).",
    clothes:"Zapatos deportivos acolchados; caminarás decenas de pasillos.",
    todo:["Ver 'La Ronda de Noche' y asomarse por el balcón de la monumental Biblioteca Cuypers"],
    cost:"Aprox 22 EUR. Gratis con la Museumkaart o I amsterdam City Card.",
    hour:"Reservar la primera franja horaria (9:00 AM) para ver a Rembrandt sin empujones.",
    effort:"Mucho tiempo de pie. Museo enorme. Tiene ascensores de cristal modernos y sillas de ruedas en préstamo gratis.",
    gear:"Cámaras permitidas pero sin flash y sin tripié/selfie stick. Audio guías descargables en el móvil (lleva audífonos).",
    logis:"Guardarropa y taquillas gratuitos y obligatorios. Baños amplios e inmaculados.",
    food:"La cafetería del museo es hermosa (café y tarta de manzana). Fuera, hay puestos de arenque (Haring) cerca de Museumplein.",
    walk:"Suelos interiores muy lisos (mármol/madera). Excelente para evitar tropiezos, pero el tamaño del museo implica caminar hasta 2 o 3 km internamente. Toma descansos frecuentes.",
    signal:"WiFi gratuito rápido dentro del museo.",
    planb:"Si llueve en el parque exterior, entra directo; es el perfecto plan bajo techo de Ámsterdam.",
    light:"No requiere. Las obras tienen iluminación de galería de alta tecnología (LED calibrado).",
    booking:"Obligatorio reservar el día y hora con al menos 1 o 2 semanas de antelación.",
    film:"Ocean's Twelve, The Fault in Our Stars." },
  { s:"van-gogh", c:"nl", w:"Museo Van Gogh", we:"Van Gogh Museum",
    n:"Museo Van Gogh", p:"van JOJ",
    d:"La colección más grande del mundo de sus obras. Boletos con horario fijo, se agotan.",
    yt:"Van Gogh Museum Amsterdam",
    why:"La colección más grande del mundo del genio postimpresionista Vincent van Gogh. Su recorrido relata la evolución emocional y técnica del artista.",
    how:"Justo al lado del Rijksmuseum en Museumplein, Ámsterdam.",
    time:"2 a 2.5 horas.",
    hist:"Construido en 1973 para alojar las obras heredadas por la familia del hermano menor de Vincent, Theo van Gogh, quien fue su mayor pilar de apoyo.",
    tips:["TOTALMENTE OBLIGATORIO comprar ticket online, no hay taquillas.", "Prohibido tomar fotografías en la mayoría de las salas de exposición.", "Las audioguías valen mucho la pena."],
    curio:"Van Gogh solo vendió una pintura ('El viñedo rojo') en vida; hoy este museo recibe a más de 2 millones de personas al año para ver su obra.",
    clothes:"Ropa casual e informal. Llevar bolsa pequeña.",
    todo:["Observar la técnica de pinceladas gruesas (empaste) en 'Los Girasoles' y 'Almendro en flor', y leer fragmentos de las conmovedoras cartas a su hermano Theo"] },
  { s:"ana-frank", c:"nl", w:"Casa de Ana Frank", we:"Anne Frank House",
    n:"Casa de Ana Frank", p:"Anne Frank Huis",
    d:"Solo se vende en línea y se agota con semanas de anticipación.",
    yt:"Anne Frank House Amsterdam",
    why:"Experiencia histórica desgarradora y esencial para entender la SGM.",
    how:"Sobre el canal Prinsengracht (centro de Ámsterdam).",
    time:"1 a 1.5 horas.",
    hist:"En julio de 1942, ante las inminentes y aterradoras redadas nazis en las calles de Ámsterdam, la familia Frank, junto con los van Pels y Fritz Pfeffer, pasaron abruptamente a la clandestinidad ocultándose en 'La casa de atrás'. Este anexo secreto estaba camuflado ingeniosamente tras un librero giratorio en las oficinas de Otto Frank. Sobrevivieron allí escondidos 761 días en completo silencio hasta ser tristemente delatados en 1944. Otto Frank, el único de los ocho que sobrevivió a los campos de exterminio, supervisó personalmente la creación del museo pidiendo que las habitaciones se mantuvieran siempre sin muebles.",
    tips:["Prohibido tomar fotografías (respeto).", "Mantener tono de voz al mínimo.", "Sentimientos fuertes."],
    curio:"El diario original (el cuaderno de cuadros rojos) está expuesto al final del recorrido.",
    clothes:"Ropa muy cómoda. Los anexos no tienen control climático moderno, hace calor en verano.",
    todo:["Cruzar el librero original y leer los recortes de revistas que Ana pegó en su pared"],
    cost:"Aprox 16 EUR. Solo online.",
    hour:"Franjas de tarde/noche para un ambiente de reflexión más íntimo.",
    effort:"Difícil. Las escaleras ocultas originales son empinadísimas (casi escaleras de mano). No es apto para sillas de ruedas ni personas con movilidad muy reducida.",
    gear:"Apagar/silenciar celulares por completo. La audioguía es entregada físicamente y es obligatoria.",
    logis:"Pequeño guardarropa (solo para bolsas chicas). Sin estacionamiento de coches cerca.",
    food:"El café 'Pancakes Amsterdam' está justo a la vuelta; los tradicionales pannenkoeken gigantes.",
    walk:"Recorrido interno muy corto y comprimido, pero en vertical. Las personas deben ser capaces de trepar escalones muy estrechos del siglo XVII (alerta para rodillas y caderas sensibles).",
    signal:"No necesitas usar datos adentro; hay que desconectarse por respeto al ambiente.",
    planb:"Actividad siempre bajo techo.",
    light:"Irrelevante.",
    booking:"CRÍTICO: Los boletos se liberan el primer martes del mes anterior y se agotan ese mismo día en horas. Poner alarma.",
    film:"The Fault in Our Stars (escena del beso)." },
  { s:"canales", c:"nl", w:"Canales de Ámsterdam", we:"Canals of Amsterdam",
    n:"Los canales", p:"Grachtengordel",
    d:"Patrimonio de la humanidad. Un paseo en barco de una hora es la mejor forma de verlos.",
    yt:"Amsterdam canal cruise",
    why:"El Anillo de Canales (Grachtengordel) es Patrimonio de la Humanidad y la arteria principal del encanto de Ámsterdam, con puentes arqueados y casas estrechas.",
    how:"Están por todo el centro histórico. Abordas barcos cerca de la Estación Central o frente al Rijksmuseum.",
    time:"Un paseo en barco dura unos 60-75 minutos.",
    hist:"Fueron construidos en el siglo XVII (Siglo de Oro) para gestión del agua, defensa y transporte comercial, expandiendo la ciudad en forma de semicírculos concéntricos.",
    tips:["Cuidado con los ciclistas al caminar cerca del borde, no tienen piedad de los turistas distraídos.", "No elegir los barcos techados gigantes (son calurosos); busca barcos pequeños abiertos.", "No tirar nada al agua."],
    curio:"Ámsterdam tiene más de 160 canales y 1,200 puentes, más que Venecia. Se recuperan unas 12,000 bicicletas del fondo de los canales cada año.",
    clothes:"En el barco puede correr viento frío, llevar una chamarra ligera. Calzado para caminar mucho.",
    todo:["Tomar un crucero en barco semi-abierto al atardecer o rentar un bote eléctrico pequeño para manejarlo tú mismo", "Fotografiar las casas torcidas y el cruce de los 7 puentes"] },
  { s:"zaanse-schans", c:"nl", w:"Zaanse Schans",
    n:"Zaanse Schans", p:"ZÁN-se sjans",
    d:"El pueblo de molinos de viento, a cuarenta minutos en tren.",
    yt:"Zaanse Schans windmills Netherlands",
    why:"Un museo vivo con molinos de viento reales que muelen pigmentos, sierran madera y prensan aceite.",
    how:"Tren desde la Estación Central de Ámsterdam hasta Zaandijk (15 min) + caminata de 15 min.",
    time:"3 a 4 horas.",
    hist:"En su apogeo en los siglos XVIII y XIX, la región pantanosa de Zaan se convirtió en la primera y más grande zona intensamente industrializada del mundo entero. Albergó una densa red de más de 600 enormes molinos de viento que funcionaban como verdaderas fábricas impulsadas por aire, procesando cacao, moliendo especias exóticas de Asia, y sobre todo, aserrando troncos velozmente para construir las inmensas flotas mercantes neerlandesas. Cuando la modernidad llegó, muchos edificios históricos de madera amenazados fueron trasladados pieza por pieza en camiones a este sitio en los años 60 para salvarlos de la demolición.",
    tips:["Hay mucho turista a partir de media mañana.", "Olor penetrante a manteca de cacao en el aire."],
    curio:"Puedes comprar pigmentos puros que fueron molidos con rocas impulsadas por aspas eólicas.",
    clothes:"Caminata plana y expuesta a la intemperie: rompevientos es obligatorio.",
    todo:["Entrar al molino aserradero (ver los engranajes) y presenciar la talla de un zueco de madera"],
    cost:"Pueblo abierto gratis. Entrar a cada molino cuesta ~6 EUR (o usar el Zaanse Schans Card).",
    hour:"Llegar a las 8:30 AM antes de que abran los molinos para caminar el pueblo vacío sin multitudes.",
    effort:"Caminata muy fácil. Senderos pavimentados de ladrillo y puentes planos. Muy amigable para movilidad asistida.",
    gear:"GoPro o gran angular para abarcar las aspas. Batería externa (se toman cientos de fotos y videos).",
    logis:"Amplio estacionamiento (pago tarifa única 15 EUR). Baños en el centro de visitantes.",
    food:"Queso Gouda o Edam ahumado en la granja y panqueques gruesos (De Kraai).",
    walk:"Desde la estación de tren hasta el centro del pueblo son unos 1.5 km (15-20 min) caminando sobre calles residenciales y un puente llano. Para evitar esto, hay un autobús directo (Bus 391) que te deja a 100 metros de la entrada.",
    signal:"Buena, pero descarga en Google Maps la ruta de caminata de la estación de tren por si acaso.",
    planb:"El Zaans Museum está cerrado e incluye pabellones interactivos techados.",
    light:"Los colores de las casas de madera (verde oscuro) se aprecian mucho más con sol.",
    booking:"No es estrictamente necesario, comprar tickets de molinos ahí mismo.",
    film:"Varias películas y documentales históricos europeos." },
  { s:"vondelpark", c:"nl", w:"Vondelpark",
    n:"Vondelpark", p:"VON-del-park",
    d:"Cruzando la calle del hotel. En octubre está en pleno color de otoño.",
    yt:"Vondelpark Amsterdam autumn",
    why:"El pulmón verde más grande y vibrante de Ámsterdam. Es el punto de encuentro de los locales para relajarse, hacer picnic y disfrutar del arte al aire libre.",
    how:"Al sur del centro, muy cerca de la Museumplein.",
    time:"1 a 2 horas (o lo que quieras relajarte).",
    hist:"Inaugurado en 1865 como el 'Nieuwe Park' y luego renombrado en honor al dramaturgo del siglo XVII Joost van den Vondel.",
    tips:["El carril de bicicletas dentro del parque es rápido, cruza con mucho cuidado.", "Mantener limpios los espacios de picnic.", "Cierra áreas en la noche profunda."],
    curio:"Es el parque más visitado de los Países Bajos (10 millones de visitantes al año) y tiene esculturas de Picasso escondidas entre los árboles.",
    clothes:"Ropa muy relajada. En verano, pantalones cortos y algo para sentarse en el pasto.",
    todo:["Rentar una bicicleta y recorrerlo entero, comprar comida en un supermercado Albert Heijn cercano y armar un picnic a orillas de los estanques, ver teatro callejero o escuchar a los músicos"] },
  { s:"haarlem", c:"nl", w:"Haarlem",
    n:"Haarlem", p:"JÁR-lem",
    d:"Ciudad chica de canales y plaza con catedral, a quince minutos en tren de Ámsterdam.",
    yt:"Haarlem Netherlands walking tour",
    why:"Conocida como una 'mini Ámsterdam', tiene la misma arquitectura histórica y canales hermosos, pero sin las multitudes aplastantes de turistas.",
    how:"A solo 15-20 minutos en tren intercity desde la Estación Central de Ámsterdam.",
    time:"Medio día o un día completo.",
    hist:"Fue el centro del comercio de los tulipanes en el siglo XVII y un importante productor de cerveza y telas.",
    tips:["Muchas tiendas pequeñas cierran el domingo o lunes por la mañana.", "Estación de tren histórica, no perderse su arquitectura Art Nouveau."],
    curio:"El barrio de Harlem en la ciudad de Nueva York recibió su nombre de esta tranquila ciudad neerlandesa, herencia de cuando Nueva York se llamaba Nueva Ámsterdam.",
    clothes:"Estilo casual europeo. Zapatos muy cómodos para caminar por el empedrado.",
    todo:["Visitar el museo Teylers (el más antiguo del país), entrar a la Grote Kerk (iglesia donde Mozart tocó el órgano a los 10 años) y explorar los 'Hofjes' (patios ajardinados ocultos medievales)"] },
  { s:"utrecht", c:"nl", w:"Utrecht",
    n:"Utrecht", p:"Ú-trej",
    d:"Canales de dos niveles con terrazas al nivel del agua y la torre más alta del país.",
    yt:"Utrecht Netherlands canals Dom tower",
    why:"Su centro medieval es atravesado por el canal Oudegracht, único en el mundo por tener un sistema de dos niveles (calle arriba, sótanos convertidos en cafés a nivel del agua).",
    how:"A 30 minutos en tren desde Ámsterdam.",
    time:"Medio día o un día completo.",
    hist:"Fue la ciudad más importante de los Países Bajos hasta la Edad de Oro, y su imponente Torre Dom fue partida a la mitad durante un tornado devastador en 1674, separándola de su iglesia.",
    tips:["Subir la Torre Dom exige subir 465 escalones estrechos (reservar tour con antelación).", "Gran cantidad de estudiantes universitarios en bici, tráfico ágil."],
    curio:"Debajo de la plaza Domplein hay túneles que revelan las ruinas romanas originales fundacionales de la ciudad.",
    clothes:"Capas urbanas. Buen calzado (Utrecht tiene empedrado irregular).",
    todo:["Bajar a las terrazas del canal (werfkelders) para tomar una cerveza local, subir la Torre Dom para vistas panorámicas y pasear en kayak por los canales céntricos"] },
  { s:"kinderdijk", c:"nl", w:"Kinderdijk",
    n:"Kinderdijk", p:"KIN-der-deik",
    d:"Diecinueve molinos del siglo XVIII alineados junto a los diques, patrimonio de la humanidad.",
    yt:"Kinderdijk windmills Netherlands",
    why:"Patrimonio Mundial de la UNESCO. Es la concentración más grande e histórica (19 molinos originales del 1740) alineados en su entorno polder original, diseñado para evitar inundaciones.",
    how:"A unos 30 min de Róterdam. Se llega idealmente tomando el Waterbus (ferry) desde Róterdam.",
    time:"2 a 3 horas.",
    hist:"Construidos en el siglo XVIII para bombear el agua fuera de las tierras bajas ubicadas por debajo del nivel del mar (pólderes), salvando a la región de hundirse.",
    tips:["Es un sendero largo y abierto, sin sombra en verano ni protección del viento en invierno.", "Rentar bici acelera mucho el recorrido.", "Respeta las zonas privadas, algunas familias aún viven en los molinos."],
    curio:"Ingeniería hidráulica pura: antes de los motores eléctricos, esta red de molinos funcionaba conectada trabajando en cadena (ascendiendo el agua en escalones) para vaciar grandes cuencas.",
    clothes:"Rompevientos (muy importante en esta llanura) y gorra/lentes de sol.",
    todo:["Caminar por los diques entre los pastizales, entrar a los dos molinos-museo para ver cómo vivían hacinadas las familias con 10 hijos y dar un paseo en barco por los canales internos"] },
  { s:"delft-la-haya", c:"nl", w:"Delft",
    n:"Delft y La Haya", p:"Delft · Den Haag",
    d:"El pueblo de la loza azul y, a diez minutos, el Mauritshuis con La joven de la perla.",
    yt:"Delft Den Haag Mauritshuis Girl with a Pearl Earring",
    why:"Combinación perfecta: Delft es el pueblo encantador natal de Vermeer famoso por su cerámica azul; La Haya es la sede de la realeza y los parlamentos, con arte de clase mundial.",
    how:"En tren: La Haya está a 50 min de Ámsterdam, y Delft está a 15 min adicionales al sur.",
    time:"Un día para combinar ambas.",
    hist:"Guillermo de Orange (padre de la patria) vivió y fue asesinado en Delft. La Haya, aunque no es la capital constitucional (Ámsterdam lo es), es la sede real del gobierno neerlandés.",
    tips:["En Mauritshuis es mejor sacar ticket online.", "El tranvía 1 conecta La Haya y Delft directamente en 20 minutos de forma muy conveniente.", "Al comprar cerámica en Delft, busca el sello 'Royal Delft' si quieres la auténtica pintada a mano (es cara)."],
    curio:"La Haya alberga el Palacio de la Paz, sede del Tribunal Internacional de Justicia de la ONU.",
    clothes:"Ropa de estilo ciudad cómoda. La Haya está cerca del mar del Norte, el clima puede ser más ventoso.",
    todo:["En La Haya: Ver de cerca 'La joven de la perla' y 'La lección de anatomía' en el museo Mauritshuis, y ver el complejo Binnenhof", "En Delft: Visitar la fábrica Royal Delft y la Plaza del Mercado"] },
  { s:"volendam-marken", c:"nl", w:"Volendam",
    n:"Volendam y Marken", p:"VÓ-len-dam · MÁR-ken",
    d:"Dos pueblos pesqueros de casas de madera unidos por un ferry de media hora.",
    yt:"Volendam Marken Netherlands day trip",
    why:"Pueblos tradicionales de pescadores muy pintorescos que mantienen vivas las costumbres antiguas. Casitas de madera coloridas, queserías y el Mar de Wadden.",
    how:"Autobuses desde la Estación Central de Ámsterdam (unos 30 min). Un ferry conecta Volendam y Marken.",
    time:"Medio día.",
    hist:"Fueron comunidades pesqueras prósperas hasta que la bahía de Zuiderzee fue cerrada en 1932 por un enorme dique, convirtiendo el mar en un lago de agua dulce (IJsselmeer).",
    tips:["Muy enfocado al turismo masivo; los fines de semana está repleto.", "Los restaurantes cerca del puerto en Volendam son caros.", "Cuidado con el fuerte olor a pescado en los puertos."],
    curio:"En Volendam todavía hay residentes mayores que usan la vestimenta tradicional en su día a día de manera auténtica, no solo para los turistas.",
    clothes:"Ropa portuaria relajada, rompevientos ligero marino.",
    todo:["Cruzar de un pueblo a otro en el ferry 'Marken Express', probar los panqueques (pannenkoeken) o el arenque crudo (haring) con cebolla, y perderse por las callejuelas verdes de Marken"] },
  { s:"mercados", c:"nl", w:"Albert Cuypmarkt", we:"Albert Cuyp Market",
    n:"Mercados de Ámsterdam", p:"Albert Cuyp · Bloemenmarkt",
    d:"El mercado de calle más grande de la ciudad y el mercado flotante de flores y bulbos.",
    yt:"Albert Cuyp Market Bloemenmarkt Amsterdam",
    why:"El corazón comercial local. Albert Cuyp es un festival gastronómico y multicultural en la calle; Bloemenmarkt es el único mercado de flores flotante del mundo.",
    how:"Ubicados en el sur y centro de Ámsterdam respectivamente, se llega caminando o en tranvía corto.",
    time:"2 horas (sumando ambos).",
    hist:"Bloemenmarkt data de 1862, cuando los comerciantes navegaban por el río Amstel trayendo flores y las vendían directamente desde sus botes.",
    tips:["CARTERISTAS (Pickpockets): Son el área con mayor robo de carteras a turistas; cuidar bolsos.", "Albert Cuyp cierra los domingos.", "Bloemenmarkt ya no vende tantas flores frescas, vende más bien bulbos y souvenirs."],
    curio:"Si compras bulbos de tulipán en Bloemenmarkt para llevar a México, asegúrate de que tengan el sello de exportación/certificación fitosanitaria o te los quitarán en la aduana.",
    clothes:"Ropa de calle normal, bolsillos seguros o cangurera pegada al cuerpo para documentos importantes.",
    todo:["Comer Stroopwafels gigantes recién hechos (y calientes) en el mercado Albert Cuyp, probar el queso trufado y comprar queso empaquetado al vacío o bulbos certificados en Bloemenmarkt"] }
];

